### ISSUE TITLE
getMeanLocationData missing

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/tomato#76]
in a bmlt root server you can pass `getMeanLocationData` to a meeting search to get the mean radius of meetings contained in that search as well as long/lats. would be nice to use this with tomato. example search https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&services[]=111&services[]=110&getMeanLocationData

**Comment by radius314** [comment]
Should just return [{data:😡}] always.

**Comment by jbraswell** [comment]
I'm going to implement this per @radius314's suggestion

**Comment by pjaudiomv** [comment]
getMeanLocationData has been removed in 3.0, closing this out

**Comment by dgershman** [comment]
was this implemented as I suggested?

**Comment by pjaudiomv** [comment]
yes i believe so, i think it should always be `[]` but @jbraswell can clarify if im wrong

**Comment by jbraswell** [comment]
@dgershman's suggestion was to always return `[{location:😡}]`. It was not implemented in this way. In fact, the option was removed completely from root server 3.x. As such, you pass `getMeanLocationData`, you just get the meetings list back, and not any location data, because it was completely removed.

Example: https://gyro.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&services%5B%5D=111&services%5B%5D=110&getMeanLocationData

**Comment by dgershman** [comment]
Looking for an Easter egg

**Comment by pjaudiomv** [comment]
yes `getMeanLocationData` should now return `[{location:😡}]`

**Comment by jbraswell** [comment]
Happy to accept a PR
